package com.lwjgl.input;

public enum Message {
    EMPTY,
    KEYDOWN,
    KEYUP,
    SHIFTKEYDOWN,
    SHIFTKEYUP,
    CTRLCOMMANDUP,
    CTRLCOMMANDDOWN,
    ALTCOMMANDUP,
    ALTCOMMANDDOWN,
    CHARINPUT,
    MOUSELEFTDOWN,
    MOUSELEFTUP,
    MOUSEMIDDLEDOWN,
    MOUSEMIDDLEUP,
    MOUSERIGHTDOWN,
    MOUSERIGHTUP,
    MOUSEOTHERDOWN,
    MOUSEOTHERUP,
    MOUSESCROLL,
    RESIZE,
    FRAMEBUFFERRESIZE,
    MINIMIZE,
    UNMINIMIZE,
    DESTROY
}